name:                buzzwords
version:             0.1.0.0
synopsis:            Analyze the predictive ability of word choice in SEC 10K filings
description:         Please see README.md
homepage:            https://github.com/githubuser/buzzwords#readme
license:             BSD3
author:              Andrew Brooks
maintainer:          example@example.com
copyright:           2017 Andrew Brooks
category:            Web
extra-source-files:
- README.md

# NB: These bounds are not rigorously tested.
#     If a resolver error occurs, you may want to attempt
#     blind adjustment.

dependencies:
  - ansi-terminal     >= 0.6  && < 1.0
  - base              >= 4.7  && < 5.0 
  - hmatrix           >= 0.17 && < 0.19
  - lens              >= 4.0  && < 5.0
  - time              >= 1.0  && < 2.0
  - vector-algorithms >= 0.7  && < 0.8
  - vector            >= 0.11 && < 0.12


executables:
  buzzwords:
    source-dirs:      src
    main:             Main.hs

# When we're ready to add tests, see
# https://github.com/sol/hpack/blob/master/package.yaml
# Consider using a mixture of hspec and quickcheck.